---
# tasks file for tomcat_pablo

- name: Ensure Java's directory exists
  file:
          path: "{{ java_directory }}"
          state: directory

- name: Install Java8
  unarchive:
          creates: "{{ java_directory }}/{{ jdk_version }}/"
          src: ../files/java.tar.gz
          dest: "{{ java_directory }}"

- name: Remove Java's installation file
  file:
          path: "{{ java_directory }}/java.tar.gz"
          state: absent

- name: Ensure Tomcat's directory exists
  file:
          path: "{{ tomcat_directory }}"
          state: directory

- name: Install Apache Tomcat
  unarchive:
          creates: "{{ tomcat_directory }}/{{ tomcat_version }}/"
          src: "../files/apache-tomcat.tar.gz"
          dest: "{{ tomcat_directory }}"

- name: Copy setenv.sh for Tomcat with environment variables
  template:
          src: setenv.sh.j2 
          dest: "{{ tomcat_directory }}/{{ tomcat_version }}/bin/setenv.sh"
          
- name: Copy TDS WAR file
  copy: 
          src: ../files/thredds.war
          dest: "{{ tomcat_directory }}/{{tomcat_version }}/webapps/"

- name: Startup server
  command: "{{ tomcat_directory }}/{{ tomcat_version }}/bin/startup.sh"
